package com.BookMyShow.app.models;

import lombok.Getter;
import lombok.Setter;
/*why abstract ? we do not intend to create the objects of this class*/
@Getter
@Setter
public abstract class  Exposed extends Audit {
    String uuid; // autogenerated at the time of the object creation
}
